version: "3.11"

services:
  django:
    build: ./
    command: python manage.py runserver 8080
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=drf

volumes:
  postgres_data: