# Generated by Django 4.1.3 on 2022-11-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('A', 'accepted'), ('D', 'done')], default='P', max_length=1),
        ),
    ]
